### ISSUE TITLE
송원 - 타 서비스 기능 분석 및 벤치마킹

### ISSUE THREAD

**Issue by masonlim7106** [YAPP-16th/Team_Web_2_Client#12]
경쟁사 파악 (경쟁우위, 차별성 도출출)

**Comment by swon3210** [comment]
## 점유율이 높은 주요 지도 앱

### 카카오 맵 / 네이버 맵

- 최적 경로 / 최소 시간 / 최소 환승 / 최소 도보 등 다양한 기준의 길찾기 기능 제공
    - 하지만 주변 장소 찾기 같은 경우, 위와 같은 여러 기준을 적용하지 못하고 오직 얼마나 떨어져 있는지만 확인해볼 수 있음

- 카카오의 경우, 주제별로 지역의 장소들을 모아둔 '테마 지도'를 제공.

## 기타 장소 추천 앱

### 어디가지또

- 가고자 하는 장소가 '반려견과 함께 갈수 있는 장소인지' 사전에 알아볼 수 있는 기능을 제공
    - 적용 : 장소를 추천해줄 때 '특정 조건을 만족하는 장소'인지를 사전에 필터링 할수 있도록 하는 기능 (주변에 주차 장소 있음, 주변에 마트가 있음, 주변에 공원이 있음...)

- 나만의 지도 만들기 기능 : 자신이 '갔다옴'표시 해둔 장소를 지도에 표시
    - 적용 : 내가 다녀온 곳을, 혹은 자주 다니는 곳을 표시하여 본인의 이동 동선 파악. 자신이 골라둔 장소들을 그 이동 동선 위에 띄워서 실제로 자신이 동선과 맞는 장소인지 파악

- 장소 카테고리 구독 기능 : 인생샷 명소, 갓종원갓맛집 등, 사람들이 찾아가보고 싶어할만한 장소들을 카테고라이징 하여 주변에 해당 카테고리에 해당하는 장소가 있는지 보여줌. 참고로, 본인이 리스트를 생성해서 다른 사람이 본인의 장소 리스트를 구독할 수 있음
    - 적용 : 조건에 맞는 장소들을 찾은 후에 본인이 지금까지 찾은 장소들과 시각적으로 쉽게 비교해볼 수 있도록 '장소 저장소' 기능을 제공

### 더치

- 여러 장소들간의 중간 지점을 찾아주는 기능
    - 적용 : 단순히 집 - 직장이 아니라 자신이 자주 가는 곳을 바탕으로 중간점을 찾아주는 기능. 해당 장소가 아니라 해당 장소 주변 버스 정류장이나 역을 기준으로

### CityMapper

- 오프라인 지도 제공 서비스 : 내 집과, 직장 등 특정 장소를 미리 저장해두고, 앱에 내장되어 있는 지도와 교통 정보를 바탕으로 인터넷이 없더라도 오프라인으로 지도 서비스를 이용할 수 있게 해줌
    - 적용 : API 를 사전에 활용하여 오프라인에서 활용할 수 있는 지도 데이터와 교통 정보 데이터를 미리 구축한 후 사용자의 인터넷 연결이 없으면 오프라인 데이터를 바탕으로 서비스가 동작하도록 함(어렵겠죠...)

### Moovit

- '내' 정거장 즐겨찾기 : 이미 등록해둔 정거장을 바탕으로 검색 없이 길찾기를 빠르게 수행
    - 적용 : 내가 자주 이용하는 정거장을 등록하고 해당 정거장에서 한번에 갈수 있는 장소들을 추천해줌

# 결론

## 기존의 서비스들은 '장소 추천 방식' 자체는 큰 차별화가 없음

- 지금까지 배포된 거의 모든 지도 / 장소 찾기 어플리케이션들은 최적 경로를 찾을 때의 주요 기준을 '장소'로 두고 서비스를 제공함. 그래서 크게는 다음의 두가지 순서를 따르게 됨

**특정 장소 선택 → 다른 장소 선택  → 필터링 기준 선택 → 필터링 기준에 맞는 경로들을 보여줌**

혹은

**특정 장소 선택 → 카테고리 선택 → 카테고리에 해당하는 주변 장소들을 보여줌**

- 반면 현재 제작하고자 하는 '찾아존'은 다음의 순서도를 따르게 됨

**특정 장소 선택 → 필터링 기준 선택 → 필터링 기준에 맞는 주변 장소들을 보여줌**

- 하지만 이를 위해선 기존의 앱들처럼 장소를 기준으로 두는 것이 아니라, '정류장'을 기준으로 장소 추천이 이루어져야 할 것이라고 생각. 기준이 되는 장소 선택을 '정류장'을 바탕으로 해야하며, 기준에 맞는 장소 추천도 '정류장'을 바탕으로 해야함.

- 따라서 (이용자가 본인이 이용할) 정류장 선택 → 필터링 기준 적용 → 조건에 맞는 정류장의 리스트가 출력 → 이용자가 해당 정류장들을 클릭해서 주변의 '부동산 매물', '마트', '공원' 등의 정보를 바탕으로 본인이 원하는 장소인지를 판단 → 적합한 장소라면 '저장소'에 저장 → 선별을 완료한 후, 저장된 장소들 중에서만 서로를 비교해보고 장소(정류장)을 선택의 순서를 따르는 방법이 있을 것으로 보임

## 개인화된 서비스 제공

- 카카오 맵, 네이버 지도와 같은 주요 지도 어플리케이션과의 차별성을 두기 위해 '개인화된 서비스'를 제공하려는 경향이 발견됨. 어디가지또가 가장 대표적인 예. 귀여운 캐릭터들과 '내가 다녀온 장소들', '내가 가고 싶은 장소들', '내가 구독한 장소 리스트' 등, 장소를 마치 사진이나 음악을 저장하는 것처럼 저장소에 모아두고 분류하는 기능을 제공함

**Comment by masonlim7106** [comment]
정류장을 기준으로 두어야하는 이유가 무엇인가요!? (주소가 아니라)
