### ISSUE TITLE
광호 - 서비스 구현 가능성 조사

### ISSUE THREAD

**Issue by masonlim7106** [YAPP-16th/Team_Web_2_Client#23]

**Comment by AnGwangHo** [comment]
# 교통관련 API 조사

### API 제공현황

1. 네이버 지도
    - [https://www.ncloud.com/product/applicationService/maps](https://www.ncloud.com/product/applicationService/maps)
    - 출발,목적지에 대한 경로 정보는 자동차만 제공(나머지는 추후 제공)
    - 네이버 지도에서 경로 검색 시 json data는 원시 data로 얻어올 수 있음(query 노출되어 있음) but 가공의 문제
2. 카카오 지도
    - [http://apis.map.kakao.com/web/guide/#routeurl](http://apis.map.kakao.com/web/guide/#routeurl)
    - 지도 링크로 연결시켜 자사 서비스에서 검색하도록 유도함
    - 직접 get 방식으로 url에 parmeter 넣는 방식으로는 data 얻어 올 수 있음
3. ODasy Lab
    - [https://lab.odsay.com/guide/guide?platform=web](https://lab.odsay.com/guide/guide?platform=web)
    - API 제공하나 무료 제한수가 존재(1000/일)
    - 유료로 지불하기에는 300만원/월 가격이 큼
4. Tmap API
    - [https://openapi.sk.com/api/detailView](https://openapi.sk.com/api/detailView)
    - 무료 제한수 (1000/일)
    - 자동차/도보 경로만 제공
5. Google Map 
    - [https://developers.google.com/maps/documentation/](https://developers.google.com/maps/documentation/)
    - 대중교통, 자전거, 운정, 도보에 대한 길찾기 검색 API 제공
    - 매달 $200무료 제공
    - 대략 1000건 요청당 $5~10 과금

### 조사 결과

- 경로찾기 API 제공
    - ODasy Lab
    - Google Map API
- 경로찾기 API 미제공
    - 네이버 지도 API
    - 카카오 지도 API
    - Tmap API

### 결론

- ODasy Lab의 경우 무료 제공량이 한정적이며 과금에 대해서 개인이 결제하기에는 부담 됨
- Google Map API의 경우 매월 $200 무료 크레딧 제공 및 가입 시 $300 크레딧 제공, 요청 트레픽에 대한 과금이 1000건/$5~10 으로 저렴(단순 길찾기 요청만으로 40,000/일 제공)

**Comment by AnGwangHo** [comment]
# 방 매물 API 조사

### API 제공 현황
- 직방, 다방, 네이버 부동산, 다음 부동산, 피터팬의 좋은 방 구하기 모두 API 미제공

### 해결방안
- 각 사이트 별 부동산 매물에 대한 크롤링 필요
   - 인터넷에 예시가 다수 존재

### 결론
- 매물에 대한 정보는 특정 주기(1d, 12h)별 auto 크롤링 수행

**Comment by swon3210** [comment]
확인했습니다!

**Comment by masonlim7106** [comment]
넵 확인했습니다 ㅎ
