### ISSUE TITLE
영지 - 타 서비스 기능 분석 및 벤치마킹

### ISSUE THREAD

**Issue by masonlim7106** [YAPP-16th/Team_Web_2_Client#24]

**Comment by otterji** [comment]
# 타 서비스 기능 분석 및 벤치마킹

### 1.  타 서비스 기능 현황 (방 구하기 서비스 관련)

#### 1) 네이버 부동산 : 
https://land.naver.com/
 - 아파트 / 빌라 / 원룸 이런식으로 필터가 걸려있음

![image](https://user-images.githubusercontent.com/52898735/75862483-6135f500-5e42-11ea-8f5a-f323f5a0e4bb.png)

   - 구역이 시 / 구 / 동으로 나누어져 있음 (동 이 최소 단위)

![image](https://user-images.githubusercontent.com/52898735/75862327-161be200-5e42-11ea-96c9-1c9bd8d09118.png)


 - 매물 정보, 실 거래가, 동호수, 학군정보 가 세부정보로 나와있음. 대신 이 창에서 공인중개사 까지 길찾기를 바로 할 수 있음!! 누르면 네이버 지도 길찾기로 바로 연동

![image](https://user-images.githubusercontent.com/52898735/75862590-87f42b80-5e42-11ea-9a3a-9c5d4d56bc72.png)

**결론** 매물의 교통 정보를 바로 연결할 수 없음! 

#### 2) 직방
: https://www.zigbang.com/
- 네이버와 똑같이 아파트, 빌라, 원룸 등의 필터가 있음
- 원하는 지역명 / 지하철역 / 단지명 을 입력하라함 (중요!!)
- 여기서 동네를 입력하면 광범위하게 보여줌
예) 영통을  검색했을 때 이런식으로 나옴

![image](https://user-images.githubusercontent.com/52898735/75863161-647db080-5e43-11ea-84ee-020fa5cbbdfb.png)

- 방 세부정보를 눌렀을 때 교통정보 탭이 있음
![image](https://user-images.githubusercontent.com/52898735/75863263-8840f680-5e43-11ea-8c88-4fe40352ffb0.png)


검색을 하면 이렇게 나옴

![image](https://user-images.githubusercontent.com/52898735/75863317-9d1d8a00-5e43-11ea-8bc7-c2b97a8dc997.png)

도착지를 여러개 설정해서 비교해서 볼 수 있음..

**결론** 우리가 하려는게 이미 있다! 


#### 3) 다방
: https://www.dabangapp.com/
- 역시나 처음에 테마를 검색하게 함. 여기는 처음에 필터가 없음

![image](https://user-images.githubusercontent.com/52898735/75863453-da821780-5e43-11ea-9c84-428532a6bd8b.png)

- 여기도 역을 입력하면 좀 좁은 단위로 방 매물을 보여줌

![image](https://user-images.githubusercontent.com/52898735/75863513-f4bbf580-5e43-11ea-9aea-1ecde4ef52b3.png)


- 위치 정보는 이정도 나오고 길 찾기 서비스는 없음! 주변 카페나 은행 등 편의시설, 안전시설, 학군 정보를 알려줌
![image](https://user-images.githubusercontent.com/52898735/75863606-1917d200-5e44-11ea-9c98-62fb3eaaab11.png)


**결론** 더 세분화된 지역정보를 보여주지만 길찾기는 없다! 대신 편의시설에 중점!

#### 4) 피터팬
: https://www.peterpanz.com/?filter=latitude:37.4762~37.4921544%7C%7Clongitude:126.9168068~126.9427706&zoomLevel=16&center=%7B%22y%22:37.4841776,%22_lat%22:37.4841776,%22x%22:126.9297887,%22_lng%22:126.9297887%7D&utm_source=google&utm_medium=cpc&dong=undefined&gungu=undefined

- 여기도 처음 검색으로 들어감

![image](https://user-images.githubusercontent.com/52898735/75863726-4bc1ca80-5e44-11ea-9574-bb1d50f3f7e4.png)

이런식으로 지도가 나오고 근처 방을 찾을 수 있게 해줌. 

- 위치 정보는 주소와 지도가 정확하게 나오지만, 어디까지와의 길찾기 기능은 없음
대신 상세 설명으로 많은 것이 적혀있음 이런식으로

![image](https://user-images.githubusercontent.com/52898735/75863845-7ca1ff80-5e44-11ea-9c04-5382bc687528.png)


**결론** 길찾기는 없지만 세부사항으로 써있다!


## 종합결론
직방에 바로 길찾기가 있다... 하지만 대다수가 처음부터 지하철역 이나 동을 검색하라고 되어있기에, 우리가 먼저 이 "검색할 지역"을 추천해줘야한다! 


## 추가적인 인터뷰

##### 질문 : 방 구하는 어플을 써봤는지, 어떤 식으로 썼는지, 교통편 검색 서비스가 있으면 사용할건지


**답변1**: 교통편 때문에 좋은 매물을 놓치고 싶지 않아서 매물을 먼저 보고 교통은 나중에 검색하는 편이다. 집이 1순위이기 때문에 집을 먼저 보고 후에 교통편을 본다. 어떤 집이 어떻게 될 줄 모르기 때문에 교통을 먼저 찾은 적은 없다. 부동산 마다 매물이 달라서, 이런 식으로 교통 먼저 보면 부동산을 더 많이 둘러봐야 할 것 같아서 불편할 것 같다.


**답변2**: 방 구하는 어플 안에 있는 거면 편하게 쓸 거 같은데, 따로 있으면 보기 불편해서 안쓸 것 같다. 위치를 검색 한 후 동네에 맞게 네이버 부동산 같은 서비스로 연결시켜 주면 좋을 것 같다.


**답변 3**: 굳이 쓰지 않을 것 같음. 어차피 목적지에 대한 최단거리나 대중교통을 검색하는 거라서. 그리고 차를 이용하기 때문에 거리순 아니면 관계가 없음. 네이버 지도에 쳐서 바로 나오는 것이 만족스러움. 매물을 찾고 바로 지도 검색하는거나, 웹 서비스로 찾고 매물을 검색하나 똑같이 시간이 많이 들 것 같음.


**답변 4**: 나는 유용하게 쓸 것 같다. 방 구할때 제일 중요한게 직장까지의 위치이기 때문.  병원이나 다른 지역이나 역으로 갈 때 대중교통을 일일이 알아보고 방 위치를 잡는게 아니라서 어플로 이 방 근처에는 5분 내에 버스정류장이 있고 주요 지하철역으로 가는 버스가 있다 이런걸 알려주면 한번에 많이 고려할 수 있으니까 좋을 것 같다. 방 근처 교통편이 몇분이고 어디로 가는게 편한지 나오면 좋을 것 같다. 애초에 교통편 좋은 부분에 몰려있는 자취방들을 보여주고 이런건 좋을 것 같다. 매물을 연결해주고 가격이나 다른 부분이 마음에 안들면 사용자가 범위를 지정해서 더 늘리고 이런식으로!



**인터뷰 결론**: (최대한 원래의 아이디어를 건드리지 않는 선에서) 

회사를 입력함 -> 사용자 입력 시간에 맞는 교통 좋은 구역을 찾아줌  -> (여기서 나아가 얘는 주요역이나 어디까지의 교통도 좋아요~ 하고 알려줌) -> 매물을 보여줌 -> 마음에 안들면 더 늘려서 추천해드릴까요? 하고 또 추천해줌. (대중교통 뿐 만이 아니고 영화관, 주요 편의시설 몇분인지 이런것도 나오면 좋을 것 같다. 참고사항)

**대신 주의할 점은 배차 45분 간격 이런걸 제외해야함 아니면 같이 알려주거나 한 달 차비까지 같이 계산해서 알려주기!!!**

# 최종 결론
1. 회사 위치를 찍고 xx 분 이내에 있는 위치를 추천해주되, 다른 방 검색 서비스에 연결할 수 있게끔 지하철역 이나 동 으로 알려줘야 할 것 같다.

2. 나아가서 내가 찾은 결과물의 위치들이 다른 곳과는 어떤 유기성이 있는지 보여주면 좋을 것 같다. (이 위치는 심지어 영화관도 ~분 거리내에 있고 편의시설 등이 몇 분 거리에 있으며~)

3. xx 분 입력한 것 내에서 매물이 마음에 안들었을 경우, 알아서 xx + 5 분 거리에 있는 위치도 추천해 드릴까요? 탭을 추가하면 좋을 것 같다.

4. 역시나 제일 중요한건, 실제 정확성이다. 배차간격이나 도보를 최대한 확실하게 반영해야  한다.

**Comment by swon3210** [comment]
확인했습니다! 집을 찾는 사람들의 대부분이 매물을 더 중요시한다면 말씀하신 것처럼 '좋은 매물을 찾는데 도움이되는 서비스다' 라는 인식을 심어줘야 하므로 기존의 서비스와 최대한 연동이 되는 방향으로 개발하는게 저도 맞자고 생각합니다!

**Comment by masonlim7106** [comment]
**전반적인 매물서비스의 특징** 
지하철역이나 동을 먼저 검색

**우리가 추구하는바** 
지하철역이나 동을 추천해준다. (O)
직방,다방,네이버부동산,피터팬을 쓰기 전에 먼저 가이드를 준다. (O)

**인터뷰**
**위치를 중요하게 여기시는 분들과 아니신 분들의 차이를 알수있어서 재밌었습니다 ㅎㅎ 
결국 '유기성' ( 타 서비스로 연결되고, 내가 궁금한것들을 더 추가로 찾아보는것) 이 핵심이 될 것 같네요

Q. 'URL로 검색내용을 연결할수있다' 에 대해서 설명을 조금 더 듣고싶습니다.
