### ISSUE TITLE
원희 - 서비스 구현 가능성 조사

### ISSUE THREAD

**Issue by masonlim7106** [YAPP-16th/Team_Web_2_Client#25]

**Comment by wonheejeong** [comment]
**1. API 조사 - 유료 API 제외하고 검색한 결과**


대중교통환승경로 조회 서비스


-버스 지하철 환승 경로 조회   
-목적지와 출발지의 버스와 지하철을 이용한 최단거리경로를 조회
-소요 시간 정보 제공
-postman으로 테스트 해본 결과 문제 없이 잘 돌아감!
https://www.data.go.kr/dataset/15000414/openapi.do

**2. 개발시 예상되는 issue**
1. 시간 기준 정렬할 경우, 오래 걸리는 zone의 데이터는 너무 크고 광범위할 것 같음
-  해결 방안 : 어느 정도 시간 이상의 거리는 제공하지 않음을 명시하기 ex) 최대 30분까지만 입력 가능...(30분도 크긴 할듯)  
- 프론트 분들 혹시 엄청 큰 규모의 데이터를 받으면 다루기가 힘들어지나요?? 서버에서 걸러줘야 하나요??

2. 소요 시간 기준 정렬관련
- 위 api는 출발지, 도착지를 입력받아 소요시간, 경로 등을 출력해줌 
그런데 출발지와 소요 시간을 입력하여 도착지를 출력 받으려면 
1) 반복해서 api를 호출하거나 
2) api를 호출해서 모든 소요시간 정보를 db에 넣어놓거나 (가능? ..ㄴ) 
- 아이디어 좀 부탁드려요 ㅎㅎ


**3. 그 외 궁금한 점**
1. 로그인 & 회원가입은 굳이 필요 없어보이는데 어떻게 생각하는지
2. 언제까지 api 문서 줘야하는지

**Comment by swon3210** [comment]
확인했습니다! 이 무료 API는 서비스를 제공하는데 활용할 중간 매개로 쓴다거나, 활용할 수 있는 방안이 많을 것 같습니다!

**Comment by masonlim7106** [comment]
- 10분-30분 정도로 범위 한정 필요성
- '출발지', '소요시간 입력 -->  `도착지' 출력 의 방법 2가지 = 가능성 여부 

- 로그인 & 회원가입은 확장성이 고려 되면 정의
